services:

    app.basic_cms.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - My custom initializer
            - ["/cms/pages", "/cms/posts", "/cms/routes"]
        tags:
            - { name: doctrine_phpcr.initializer }

    app.basic_cms.admin.page:
        class: AppBundle\Admin\PageAdmin
        arguments:
            - ''
            - AppBundle\Document\Page
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Basic CMS', label: Page }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    app.basic_cms.admin.post:
        class: AppBundle\Admin\PostAdmin
        arguments:
            - ''
            - AppBundle\Document\Post
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Basic CMS', label: 'Blog Posts' }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    app.basic_cms.menu_provider:
        class: Symfony\Cmf\Bundle\MenuBundle\Provider\PhpcrMenuProvider
        arguments:
            - '@cmf_menu.factory'
            - '@doctrine_phpcr'
            - /cms/pages
        calls:
            - [setRequest, ["@?request="]]
        tags:
            - { name: knp_menu.provider }
